# Build and test ASP.NET projects.
# NB: Needs OWASP Dependency checker and White source bolt tasks which have to be added to Azure Devops from the marketplace
# Variables marked (CHANGEME) need to be set up in Azure Devops Variables tab
# Whitesource bolt needs activation to run. See video here: https://bolt.whitesourcesoftware.com/whitesource-bolt-azure-devops#activate (You don't need to select to receive emails)
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ApprovalEmailAddresses: '(CHANGEME)'
  AzureLocation: '(CHANGEME)'
  AzureSubscription: '(CHANGEME)' # Same as ResourceGroup?
  Release.EnvironmentName: 'Integration' # This is so the web deployment xml transformation works
  ResourceGroup: '(CHANGEME)'

stages: 
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2019
      timeoutInMinutes: 180
      demands:
      - msbuild
      - visualstudio
      - vstest
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1
    
    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        restoreSolution: '$(solution)'
    
    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:OutDir=$(build.stagingDirectory) /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: VSTest@2
      displayName: 'Run Unit tests'
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        pathtoCustomTestAdapters: '$(build.sourcesdirectory)/packages/NUnit3TestAdapter.3.16.1/build/net35/'
        testAssemblyVer2: |
          **\SecurityEssentials.Unit.Tests.dll
          !**\*TestAdapter.dll
          !**\obj\**'
        searchFolder: '$(build.sourcesdirectory)'
        runInParallel: true
        codeCoverageEnabled: true
        diagnosticsEnabled: True

    - task: dependency-check-build-task@5
      displayName: 'OWASP Dependency Checker'
      inputs:
        projectName: 'Security Essentials'
        scanPath: '$(System.DefaultWorkingDirectory)'
        format: 'HTML'         

    - task: WhiteSource Bolt@20
      displayName: 'Whitesource bolt'
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)'
        
    - task: PublishSymbols@1
      displayName: 'Publish symbols path'
      inputs:
        SearchPattern: '**\bin\**\*.pdb'
    
    - task: CopyFiles@2
      displayName: 'Copy Application Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**\\bin\\$(BuildConfiguration)\\**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: CopyFiles@2
      displayName: 'Copy Test Adapter to $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\packages\NUnit3TestAdapter.3.16.1\'
        TargetFolder: '$(build.artifactstagingdirectory)\Tests\NUnit3TestAdapter.3.16.1\'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Approve deployment
    pool: server
    steps:
    - task: ManualIntervention@8
      displayName: 'Approve deployment to test'
      inputs:
        instructions: 'Ready to deploy to $(Release.EnvironmentName) and run acceptance tests?'
        emailRecipients: '$(ApprovalEmailAddresses)'
  - deployment: DeployWeb
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
      - visualstudio
      - vstest  
    # creates an environment if it doesn’t exist
    environment: 'integration'
    strategy:
      runOnce:
        deploy:          
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Azure Resource Group'
            inputs:
              azureSubscription: '$(AzureSubscription)'
              resourceGroupName: '$(ResourceGroup)'
              location: '$(AzureLocation)'
              csmFile: '$(build.sourcesdirectory)\src\Deploy\template.json'
              csmParametersFile: '$(build.sourcesdirectory)\src\Deploy\$(ArmTemplateParameterFile)'
              deploymentOutputs: ArmTemplateOutput
    # TODO: Deploy an instance to Azure and then run integration tests against it